### ISSUE TITLE
Rotating Calipers Failure Case

### ISSUE THREAD

**Issue by KirbyG** [ufkapano/planegeometry#1]
The rotating calipers function outputs points with distance root(8) instead of root(10) when called on [Point(3, 1), Point(2, 0), Point(0, 2), Point(1, 2)].

**Comment by ufkapano** [comment]
Hello,

Anti-clockwise orientation of points is required in the function iter_all_antipodal_pairs().
I added a new test. For your point list
L = [Point(2, 0), Point(3, 1), Point(1, 2), Point(0, 2)]
the resulting pairs are
[(Point(2, 0), Point(3, 1)),
(Point(2, 0), Point(1, 2)),
(Point(2, 0), Point(0, 2)),
(Point(3, 1), Point(0, 2))]

Regards,
Andrzej
